/* eslint-disable perfectionist/sort-objects */
export const minifyConfig = {
  exceptionUrls: false,
  htmlMinifier: {
    includeAutoGeneratedTags: true,
    collapseBooleanAttributes: true,
    collapseWhitespace: true,
    removeAttributeQuotes: false,
    removeComments: true,
    removeEmptyAttributes: false,
    minifyCSS: true,
    minifyJS: true,
    sortAttributes: true,
    sortClassName: true,
    useShortDoctype: true,
    removeRedundantAttributes: true,
  },
  override: true,
};
